name: Build installers

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: installers-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/ci.yml
    with:
      package: true
